[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hackthon_program = "2RKBndJAMhMAq2E5bZyDGQsKDcuTkWAGTTBfmrhbNxG2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jax/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
